### ISSUE TITLE
Why can't I copy the example code after installation? thank you for your reply

### ISSUE THREAD

**Issue by hjllsd** [pytdbot/client#1]
E:\pythonProject\tg-td\venv\Scripts\python.exe E:\pythonProject\tg-td\main.py 
[INFO][p 432 MainThread][1679412951.684244][tdjson.py:39][__init__]  Initializing TDjson client with library: C:\Windows\system32\tdjson.dll
[INFO][p 432 MainThread][1679412951.699214][tdjson.py:80][_build_client]  Using TDLib 1.8.12 (70bee089d)
Traceback (most recent call last):
  File "E:\pythonProject\tg-td\main.py", line 69, in <module>
    client.run()
  File "E:\pythonProject\tg-td\venv\lib\site-packages\pytdbot\client.py", line 433, in run
    self._register_signal_handlers()
  File "E:\pythonProject\tg-td\venv\lib\site-packages\pytdbot\client.py", line 1106, in _register_signal_handlers
    self.loop.add_signal_handler(sig, _handle_signal)
  File "D:\software\Microsoft Visual Studio\Shared\Python39_64\lib\asyncio\events.py", line 539, in add_signal_handler
    raise NotImplementedError
NotImplementedError

进程已结束,退出代码1
This is an echo robot example, the code is copied as it is, only the ID is changed
My technique is not good enough. If possible, please answer.
thanks

**Comment by AYMENJD** [comment]
I've pushed a fix, could you install Pytdbot again using `pip install git+https://github.com/pytdbot/client.git`?

**Comment by hjllsd** [comment]
My test didn't work, but Ubuntu 20.4 can run (not rule out my technical problem), I think it's a problem with the win system, and if it's convenient, can I add a global proxy, the global proxy seems incompatible in countries where tg can't be used this program (not sure)
By the way, paste the result of my operation
`(venv) dawn@ubuntu:~/PycharmProjects/pythonProject$ python3 main.py 
[ 2][t 1][1679477557.537161350][TdDb.cpp:389][#1][!RunOnSchedulerWorker]        Set PRAGMA user_version = 14
[ 2][t 4][1679477557.561777353][AuthDataShared.cpp:115][#1][!Td]        DcId{1} [auth_key_id:12727280648824153263][state:NoAuth][created_at:1679477188][last_used:1679594189]
[ 2][t 4][1679477557.585818290][Session.cpp:269][#1][!SessionProxy:1:main]      Generate new session_id 16693300719004550022 for auth key 12727280648824153263 for main DC1
Welcome to Pytdbot (v0.8.1). Copyright (c) 2022-2023 AYMEN Mohammed ~ https://github.com/AYMENJD
Pytdbot is free software and comes with ABSOLUTELY NO WARRANTY. Licensed under the terms of MIT License.


[ 2][t 4][1679477687.514628171][Session.cpp:628][#1][!Session:1:main]   Session connection with 3 pending requests was closed: [PosixError : Connection timed out : 110 : Error on [fd:23]] Session:1:main::Connect::TCP::[149.154.175.55:443] to DcId{1} from [192.168.1.5:37080]
Task exception was never retrieved
future: <Task finished name='Task-46' coro=<Client.__handle_authorization_state() done, defined at /home/dawn/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/pytdbot/client.py:770> exception=AuthorizationError('ACCESS_TOKEN_INVALID')>
Traceback (most recent call last):
  File "/home/dawn/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/pytdbot/client.py", line 788, in __handle_authorization_state
    await self.__handle_authorization_state_wait_phone_number()
  File "/home/dawn/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/pytdbot/client.py", line 931, in __handle_authorization_state_wait_phone_number
    raise AuthorizationError(res["message"])
pytdbot.exception.AuthorizationError: ACCESS_TOKEN_INVALID
^C[ 2][t 4][1679478655.171448230][Td.cpp:3454][#1][!Td] Close Td in state 1`
Looking forward to your reply again

**Comment by AYMENJD** [comment]
> My test didn't work

Unfortunately, i don't use TDLib in windows to test it on my own.

> pytdbot.exception.AuthorizationError: ACCESS_TOKEN_INVALID

It seems like you are passing an invalid bot token

**Comment by hjllsd** [comment]
Thank you for your patience
I have solved the problem
I would like to make three suggestions for improvement
1: Add windows support
2: Provide pre-compiled TDLib files
3: There is an official group communication
Thanks again for your patience

**Comment by AYMENJD** [comment]
@hjllsd Here is a group for further discussion: https://t.me/pytdbotchat.
